"""Chip2Dose: organ-chip readout -> human-dose margin with uncertainty, tested against the clinic.

    python run_demo.py                       # everything: tables, figures, validation, summary
    python run_demo.py --compound troglitazone
    python run_demo.py --pair troglitazone pioglitazone
    python run_demo.py --skip-validation     # margins and figures only (seconds)
"""

from __future__ import annotations

import argparse
import json
import sys
import time
import warnings
from pathlib import Path

import pandas as pd

from src import compound, config, figures, liver, load, neural, pod, validate

HERO_PAIR = ("troglitazone", "pioglitazone")


def write_csv(frame: pd.DataFrame, name: str) -> Path:
    path = config.RESULTS / name
    path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(path, index=False, float_format="%.6g", lineterminator="\n")
    return path


def public(result: dict) -> dict:
    """Drop in-memory arrays (the per-drug model scores stay inside the validation figures)."""
    return {k: v for k, v in result.items() if not k.startswith("_")}


def run_crosschecks() -> list[dict]:
    checks = pod.all_checks()
    rows = [{k: v for k, v in c.items() if k != "mismatches"} for c in checks]
    details = [{"check": c["check"], "mismatch": m} for c in checks for m in c["mismatches"]]
    write_csv(pd.DataFrame(rows), "crosschecks.csv")
    write_csv(pd.DataFrame(details, columns=["check", "mismatch"]), "crosscheck_mismatches.csv")
    write_csv(pod.named_rederivations(), "pod_rederivations.csv")
    return checks


def run_liver(pair: tuple[str, str]) -> tuple[pd.DataFrame, pd.DataFrame]:
    margins = liver.margin_table()
    pairs = liver.pair_table(margins)
    write_csv(margins, "liver_margin_table.csv")
    write_csv(pairs, "pair_table.csv")
    figures.pair_view(margins, *pair, config.RESULTS / "pair_view.png")
    matched = {tuple(sorted(p)) for p in zip(margins["key"], margins["partner_key"]) if p[1]}
    for a, b in sorted(matched):
        figures.pair_view(margins, a, b, config.RESULTS / "pairs" / f"pair_{a}_{b}.png")
    figures.liver_overview(margins, config.RESULTS / "liver_margins.png")
    return margins, pairs


def run_neural() -> tuple[pd.DataFrame, pd.DataFrame]:
    potency, margins = neural.margin_table()
    write_csv(potency, "neural_potency_table.csv")
    write_csv(margins, "neural_margin_table.csv")
    figures.neural_figure(margins, len(potency), int(potency["active"].sum()), config.RESULTS / "neural_margins.png")
    return potency, margins


def run_validation() -> dict:
    out = {}
    for endpoint in ("wide", "narrow"):
        result = validate.evaluate(endpoint)
        exploratory = validate.evaluate_exploratory(endpoint)
        write_csv(pd.DataFrame(result["arms"]), f"validation_{endpoint}_arms.csv")
        write_csv(pd.DataFrame(result["comparisons"]), f"validation_{endpoint}_comparisons.csv")
        write_csv(pd.DataFrame(exploratory["arms"] + exploratory["comparisons"]), f"exploratory_{endpoint}.csv")
        if endpoint == "wide":
            figures.roc_figure(result, exploratory, config.RESULTS / "roc.png")
            figures.paired_difference_figure(result, exploratory, config.RESULTS / "paired_difference.png")
            write_csv(validate.coefficients(result["_table"], result["_y"]), "model_coefficients.csv")
            write_csv(validate.failure_cases(result), "failure_cases.csv")
        out[endpoint] = {"preregistered": public(result), "exploratory": public(exploratory)}
    (config.RESULTS / "validation.json").write_text(json.dumps(out, indent=2, default=float) + "\n", encoding="utf-8")
    return out


def summary_text(checks, liver_margins, pairs, neural_potency, neural_margins, validation) -> str:
    lines = ["# Chip2Dose results (generated by run_demo.py; do not edit)", ""]
    lines += ["## Cross-checks (published values re-derived from their inputs)", ""]
    lines += [f"- {c['check']}: {c['n_checked']} checked, {c['n_mismatch']} mismatches ({c['tolerance']})" for c in checks]
    hero = pairs[pairs["pair"].str.lower().str.contains(HERO_PAIR[0])]
    lines += ["", "## Liver-Chip (27 drugs, Ewart et al. 2022)", ""]
    for _, row in liver_margins[liver_margins["key"].isin(HERO_PAIR)].iterrows():
        lines.append(f"- {row['result_line']}")
    if not hero.empty:
        h = hero.iloc[0]
        lines.append(f"- Pair {h['pair']}: potency differs {h['potency_fold']:.3g}-fold, free margin differs "
                     f"{h['margin_fold']:.3g}-fold; margin orders the pair like the clinic: {h['margin_orders_like_clinic']}; "
                     f"opposite verdicts: {h['opposite_verdicts']}.")
    counts = liver_margins["verdict"].value_counts().to_dict()
    lines.append(f"- Free-margin verdicts against 375: {counts}")
    if validation:
        lines += ["", "## Validation (pre-registered; see validation/preregistration.json)", ""]
        for endpoint, blocks in validation.items():
            pre = blocks["preregistered"]
            lines.append(f"### Endpoint: {endpoint} (n = {pre['n']}: {pre['n_positive']} concern, {pre['n_negative']} no concern)")
            lines += [f"- {a['arm']}: AUC {a['auc']:.3f} [{a['ci_low']:.3f}, {a['ci_high']:.3f}]" for a in pre["arms"]]
            lines += [f"- {'PRIMARY ' if c['primary'] else ''}{c['comparison']}: {c['delta_auc']:+.3f} "
                      f"[{c['ci_low']:+.3f}, {c['ci_high']:+.3f}]" for c in pre["comparisons"]]
            lines.append(f"- Outcome case: {pre['outcome_case']}")
            ex = blocks["exploratory"]
            lines.append(f"- Exploratory ({ex['status']}):")
            lines += [f"  - {a['arm']}: AUC {a['auc']:.3f} [{a['ci_low']:.3f}, {a['ci_high']:.3f}]" for a in ex["arms"]]
            lines += [f"  - {c['comparison']}: {c['delta_auc']:+.3f} [{c['ci_low']:+.3f}, {c['ci_high']:+.3f}]"
                      for c in ex["comparisons"]]
            lines.append("")
    lines += ["## Neural network-formation chip (EPA MEA)", "",
              f"- {len(neural_potency)} chemicals, {int(neural_potency['active'].sum())} active; "
              f"{neural_margins['compound'].nunique()} with an exposure comparator and a margin with band.",
              "- No published convention threshold exists for this endpoint; no verdicts are issued.", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--compound", help="describe one compound and exit")
    parser.add_argument("--pair", nargs=2, metavar=("DRUG_A", "DRUG_B"), help="pair for the pair view")
    parser.add_argument("--skip-validation", action="store_true")
    args = parser.parse_args(argv)
    warnings.simplefilter("ignore")

    if args.compound:
        print("\n".join(compound.describe(args.compound)))
        return 0

    pair = tuple(load.normalize_name(p) for p in args.pair) if args.pair else HERO_PAIR
    started = time.time()
    print("cross-checks ..."); checks = run_crosschecks()
    print("liver-chip margins and pair views ..."); liver_margins, pairs = run_liver(pair)
    print("neural-chip margins ..."); neural_potency, neural_margins = run_neural()
    validation = {}
    if not args.skip_validation:
        print("pre-registered validation (about a minute) ..."); validation = run_validation()
    summary = summary_text(checks, liver_margins, pairs, neural_potency, neural_margins, validation)
    (config.RESULTS / "summary.md").write_text(summary, encoding="utf-8")
    print(summary)
    print(f"done in {time.time() - started:.0f} s; outputs in {config.RESULTS.relative_to(config.ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
