"""Chip2Dose: organ-chip readout -> human-dose margin with uncertainty, tested against the clinic.

    python run_demo.py                       # everything: tables, figures, validation, summary
    python run_demo.py --compound troglitazone
    python run_demo.py --pair clozapine olanzapine          # one extra pair figure, seconds
    python run_demo.py --readout 12 --cmax 0.8 --fu-plasma 0.05 --fu-medium 0.7   # your own chip value
    python run_demo.py --skip-validation     # margins and figures only; summary.md is left untouched
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import math
import sys
import time
import warnings
from pathlib import Path

import pandas as pd

from src import compound, config, figures, liver, load, margin, neural, output, pod, validate

HERO_PAIR = ("troglitazone", "pioglitazone")


def write_csv(frame: pd.DataFrame, name: str) -> Path:
    path = config.RESULTS / name
    return output.atomic_write(
        path, lambda tmp: frame.to_csv(tmp, index=False, float_format="%.6g", lineterminator="\n")
    )


def public(result: dict) -> dict:
    """Drop in-memory arrays (the per-drug model scores stay inside the validation figures)."""
    return {k: v for k, v in result.items() if not k.startswith("_")}


def run_crosschecks() -> list[dict]:
    checks = pod.all_checks()
    rows = [{k: v for k, v in c.items() if k != "mismatches"} for c in checks]
    details = [{"check": c["check"], "mismatch": m} for c in checks for m in c["mismatches"]]
    write_csv(pd.DataFrame(rows), "crosschecks.csv")
    write_csv(pd.DataFrame(details, columns=["check", "mismatch"]), "crosscheck_mismatches.csv")
    write_csv(pod.named_rederivations(), "pod_rederivations.csv")
    return checks


def input_problems() -> list[str]:
    """Checksum every input before any number is computed (data/fetch.py is not a package)."""
    spec = importlib.util.spec_from_file_location("fetch", config.DATA / "fetch.py")
    fetch = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(fetch)
    return fetch.verify_cached()


def run_liver() -> tuple[pd.DataFrame, pd.DataFrame]:
    margins = liver.margin_table()
    pairs = liver.pair_table(margins)
    write_csv(margins, "liver_margin_table.csv")
    write_csv(pairs, "pair_table.csv")
    figures.pair_view(margins, *HERO_PAIR, config.RESULTS / "pair_view.png")
    figures.dose_view(margins, pairs, *HERO_PAIR, config.RESULTS / "dose_view.png")
    matched = {tuple(sorted(p)) for p in zip(margins["key"], margins["partner_key"]) if p[1]}
    for a, b in sorted(matched):
        figures.pair_view(margins, a, b, config.RESULTS / "pairs" / f"pair_{a}_{b}.png")
    figures.liver_overview(margins, config.RESULTS / "liver_margins.png")
    return margins, pairs


def run_neural() -> tuple[pd.DataFrame, pd.DataFrame]:
    potency, margins = neural.margin_table()
    write_csv(potency, "neural_potency_table.csv")
    write_csv(margins, "neural_margin_table.csv")
    figures.neural_figure(margins, len(potency), int(potency["active"].sum()), config.RESULTS / "neural_margins.png")
    return potency, margins


def run_validation() -> dict:
    out = {}
    for endpoint in ("wide", "narrow"):
        result = validate.evaluate(endpoint)
        exploratory = validate.evaluate_exploratory(endpoint)
        write_csv(pd.DataFrame(result["arms"]), f"validation_{endpoint}_arms.csv")
        write_csv(pd.DataFrame(result["comparisons"]), f"validation_{endpoint}_comparisons.csv")
        write_csv(pd.DataFrame(exploratory["arms"] + exploratory["comparisons"]), f"exploratory_{endpoint}.csv")
        if endpoint == "wide":
            figures.roc_figure(result, exploratory, config.RESULTS / "roc.png")
            figures.paired_difference_figure(result, exploratory, config.RESULTS / "paired_difference.png")
            write_csv(validate.coefficients(result["_table"], result["_y"]), "model_coefficients.csv")
            write_csv(validate.failure_cases(result), "failure_cases.csv")
        out[endpoint] = {"preregistered": public(result), "exploratory": public(exploratory)}
    output.atomic_write_text(config.RESULTS / "validation.json", json.dumps(out, indent=2, default=float) + "\n")
    return out


def summary_text(checks, liver_margins, pairs, neural_potency, neural_margins, validation) -> str:
    lines = ["# Chip2Dose results (generated by run_demo.py; do not edit)", ""]
    lines += ["## Cross-checks (published values re-derived from their inputs)", ""]
    lines += [f"- {c['check']}: {c['n_checked']} checked, {c['n_mismatch']} mismatches ({c['tolerance']})" for c in checks]
    hero = pairs[pairs["pair"].str.lower().str.contains(HERO_PAIR[0])]
    lines += ["", "## Liver-Chip (27 drugs, Ewart et al. 2022)", ""]
    for _, row in liver_margins[liver_margins["key"].isin(HERO_PAIR)].iterrows():
        lines.append(f"- {row['result_line']}")
        if pd.notna(row["equivalent_dose_mg"]):
            lines.append(f"  - {row['compound']}: chip-toxic concentration reached at {row['equivalent_dose_mg']:,.3g} mg/day "
                         f"(band {row['equivalent_dose_band_low']:,.3g}-{row['equivalent_dose_band_high']:,.3g}) vs "
                         f"{row['clinical_dose_mg']:g} mg prescribed (linear PK assumed)")
    if not hero.empty:
        h = hero.iloc[0]
        lines.append(f"- Pair {h['pair']}: potency differs {h['potency_fold']:.3g}-fold, free margin differs "
                     f"{h['margin_fold']:.3g}-fold; margin orders the pair like the clinic: {h['margin_orders_like_clinic']}; "
                     f"opposite verdicts: {h['opposite_verdicts']}.")
    counts = liver_margins["verdict"].value_counts().to_dict()
    lines.append(f"- Free-margin verdicts against 375: {counts}")
    if validation:
        lines += ["", "## Validation (pre-registered; see validation/preregistration.json)", ""]
        for endpoint, blocks in validation.items():
            pre = blocks["preregistered"]
            lines.append(f"### Endpoint: {endpoint} (n = {pre['n']}: {pre['n_positive']} concern, {pre['n_negative']} no concern)")
            lines += [f"- {a['arm']}: AUC {a['auc']:.3f} [{a['ci_low']:.3f}, {a['ci_high']:.3f}]" for a in pre["arms"]]
            lines += [f"- {'PRIMARY ' if c['primary'] else ''}{c['comparison']}: {c['delta_auc']:+.3f} "
                      f"[{c['ci_low']:+.3f}, {c['ci_high']:+.3f}]" for c in pre["comparisons"]]
            lines.append(f"- Outcome case: {pre['outcome_case']}")
            ex = blocks["exploratory"]
            lines.append(f"- Exploratory ({ex['status']}):")
            lines += [f"  - {a['arm']}: AUC {a['auc']:.3f} [{a['ci_low']:.3f}, {a['ci_high']:.3f}]" for a in ex["arms"]]
            lines += [f"  - {c['comparison']}: {c['delta_auc']:+.3f} [{c['ci_low']:+.3f}, {c['ci_high']:+.3f}]"
                      for c in ex["comparisons"]]
            lines.append("")
    lines += ["## Neural network-formation chip (EPA MEA)", "",
              f"- {len(neural_potency)} chemicals, {int(neural_potency['active'].sum())} active; "
              f"{neural_margins['compound'].nunique()} with an exposure comparator and a margin with band.",
              "- No published convention threshold exists for this endpoint; no verdicts are issued.", ""]
    return "\n".join(lines)


def run_pair(drugs: list[str]) -> int:
    """One extra pair figure; never touches the canonical pair_view.png."""
    a, b = (load.normalize_name(d) for d in drugs)
    margins = liver.margin_table()
    known = set(margins["key"])
    missing = [d for d, k in zip(drugs, (a, b)) if k not in known]
    if missing:
        print(f"Not in the Liver-Chip set: {', '.join(missing)}. Pair views need chip data for both drugs; "
              f"available: {', '.join(sorted(margins['compound']))}.")
        return 1
    if a == b:
        print("A pair needs two different drugs.")
        return 1
    path = figures.pair_view(margins, a, b, config.RESULTS / "pairs" / f"pair_{'_'.join(sorted((a, b)))}.png")
    print(f"wrote {path.relative_to(config.ROOT)}")
    return 0


def run_readout(args: argparse.Namespace) -> int:
    """A lab's own chip value: POD (uM) + clinical Cmax (uM), optional fractions unbound."""
    fu_plasma = None if args.fu_plasma is None else margin.Quantity.exact(args.fu_plasma, "user fu plasma")
    assumptions = [] if args.fu_plasma is not None else ["fraction unbound in plasma not given"]
    inp = margin.MarginInput(
        name=args.name,
        pod=margin.point_with_default(args.readout, "chip POD (user)")[0],
        cmax=margin.Quantity.exact(args.cmax, "clinical Cmax (user)") if args.cmax else None,
        fu_plasma=fu_plasma,
        fu_medium=margin.Quantity.exact(args.fu_medium, "user fu medium"),
        pod_censored=args.censored,
        dose_mg=args.dose_mg,
        assumptions=["chip POD: single value, 3-fold uncertainty assumed"] + assumptions,
    )
    for threshold in (config.THRESHOLDS["liver_free_375"], config.THRESHOLDS["liver_total_50"]):
        result = margin.compute(inp, threshold)
        print(result.line)
    if args.dose_mg is not None and result.equivalent_dose_mg is None:
        if not (math.isfinite(args.dose_mg) and args.dose_mg > 0):
            print(f"No equivalent daily dose: --dose-mg {args.dose_mg:g} is not a positive dose.")
        else:
            print("No equivalent daily dose: no margin was computed, for the reason given above.")
    elif result.equivalent_dose_mg is not None:
        lo, hi = result.equivalent_dose_band
        bound = ">" if args.censored else ""
        note = " (lower bound: no toxicity was seen up to the readout)" if args.censored else ""
        print(f"Chip-derived daily dose: {bound}{margin.fmt_dose(result.equivalent_dose_mg)} mg "
              f"(band {bound}{margin.fmt_dose(lo)} to {bound}{margin.fmt_dose(hi)} mg) "
              f"against {margin.fmt_dose(args.dose_mg)} mg, linear PK assumed{note}.")
    for note in result.assumptions:
        print(f"  assumption: {note}")
    print("Thresholds are Liver-Chip conventions (Ewart et al. 2022); for another organ, read the margin, not the verdict.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--compound", help="describe one compound and exit")
    mode.add_argument("--pair", nargs=2, metavar=("DRUG_A", "DRUG_B"), help="render one extra pair view and exit")
    mode.add_argument("--readout", type=float, metavar="POD_UM", help="your chip's lowest toxic concentration (uM)")
    parser.add_argument("--cmax", type=float, metavar="UM", help="with --readout: clinical total Cmax (uM)")
    parser.add_argument("--fu-plasma", type=float, help="with --readout: fraction unbound in plasma")
    parser.add_argument("--fu-medium", type=float, default=1.0, help="with --readout: fraction unbound in chip medium (default 1)")
    parser.add_argument("--dose-mg", type=float, help="with --readout: clinical daily dose belonging to --cmax")
    parser.add_argument("--censored", action="store_true", help="with --readout: no toxicity seen up to the value")
    parser.add_argument("--name", default="your compound", help="with --readout: label for the output")
    parser.add_argument("--skip-validation", action="store_true")
    args = parser.parse_args(argv)
    warnings.simplefilter("ignore")

    readout_only = {"--cmax": args.cmax, "--fu-plasma": args.fu_plasma, "--dose-mg": args.dose_mg,
                    "--censored": args.censored or None}
    stray = [flag for flag, value in readout_only.items() if value is not None]
    if stray and args.readout is None:
        print(f"{', '.join(stray)} only apply with --readout.")
        return 1
    if args.compound is not None and not args.compound.strip():
        print("--compound needs a drug name.")
        return 1
    if args.readout is not None:
        return run_readout(args)
    problems = input_problems()
    if problems:
        print("Input data are missing or changed; run `make data` first:\n  " + "\n  ".join(problems))
        return 2
    if args.compound is not None:
        print("\n".join(compound.describe(args.compound)))
        return 0
    if args.pair:
        return run_pair(args.pair)

    started = time.time()
    print("cross-checks ..."); checks = run_crosschecks()
    print("liver-chip margins and pair views ..."); liver_margins, pairs = run_liver()
    print("neural-chip margins ..."); neural_potency, neural_margins = run_neural()
    validation = {}
    if not args.skip_validation:
        print("pre-registered validation (the slow step: minutes on a laptop) ..."); validation = run_validation()
    summary = summary_text(checks, liver_margins, pairs, neural_potency, neural_margins, validation)
    if validation:
        output.atomic_write_text(config.RESULTS / "summary.md", summary)
    else:
        print("(--skip-validation: results/summary.md left unchanged)")
    print(summary)
    print(f"done in {time.time() - started:.0f} s; outputs in {config.RESULTS.relative_to(config.ROOT)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
